# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-25 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0002_auto_20161102_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 8, 25, 18, 33, 10, 262138))),
                ('person_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Enter', 'Enter'), ('Exit', 'Exit')], max_length=5)),
            ],
        ),
    ]
