# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-26 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0003_attendancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 12, 48, 38, 517883)),
        ),
    ]
